### ISSUE TITLE
tiktok does not embed anymore

### ISSUE THREAD

**Issue by degu-Tanya** [adryd325/discord-twitter-video-embeds#6]
![bilde](https://user-images.githubusercontent.com/100243423/155551379-6c858546-e4ed-42a0-bafc-d1680a03cc42.png)
twitter and reddit works but not tiktok

**Comment by adryd325** [comment]
I'll need to rewrite tiktok video downloading cause they changed how things work on their end. It's not a high-priority at the moment for me since I'm primarily focused on school stuff. The bot is planned to be shut down once Discord requires applying for message content intents since they rejected my application twice.

**Comment by adryd325** [comment]
TikTok has a temporary fix on the main branch, but I'm not gonna deploy the changes to my instance since it gets me IP banned from TikTok about once a week
